Features Common to all Programs
  * See the :ref:`prerequisites` section.
  * Each program requires a total of 30 credit hours, generally 10 three-credit courses. 
  * Students can receive up to 6 credit hours (replacing two of our courses) 
    for graduate work taken elsewhere: See :ref:`transfer_credit` for details. 
  * **Students who have taken undergraduate Loyola classes**: 
    Many 400-level courses in the department have closely related 300-level analogues, 
    e.g. Comp 443 and 343. Students who enter the MS program after taking 
    a Loyola course in this category 
    must choose to take 400-level courses that are not closely related to any 
    300-level courses taken earlier, unless they have GPD permission.
