General Electives
~~~~~~~~~~~~~~~~~~~~~~~~~~~

These electives are common for all programs.
 
Each program allows electives for many of the credits.  For each
program electives can be any COMP 400 level class or any CSIS class 
(courses actually taught in the Business School).

Students may take up to a maximum of 6 credit hours of 
Comp 490: Independent Project and/or Comp 499: Internship.

There are numerous options for independent study, 
including a programming project, research, or a service-oriented project.
